services:
  postgres:
    image: postgres:17.4
    env_file:
      - .env.development
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
